# Minted by spark-craft-lab. Safe to edit; destroyed with the instance.

CRAFT_APP_ID={{APP_ID}}
CRAFT_ENVIRONMENT=dev
CRAFT_SECURITY_KEY={{SECURITY_KEY}}

CRAFT_DB_DRIVER={{DB_DRIVER}}
CRAFT_DB_SERVER={{DB_SERVER}}
CRAFT_DB_PORT={{DB_PORT}}
CRAFT_DB_DATABASE={{DB_NAME}}
CRAFT_DB_USER={{DB_USER}}
CRAFT_DB_PASSWORD={{DB_PASSWORD}}
{{DB_SCHEMA_LINE}}CRAFT_DB_TABLE_PREFIX=

REDIS_HOSTNAME=redis
REDIS_PORT=6379
REDIS_PASSWORD=root

DEV_MODE=true
ALLOW_ADMIN_CHANGES=true
DISALLOW_ROBOTS=true

APP_URL=http://localhost:{{WEB_PORT}}

MAILPIT_HOST=mailpit
MAILPIT_SMTP_PORT=1025
